// import './globals.css'
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import { Providers } from "@/store/Provider";
import PropTypes from "prop-types";

type RootLayoutProps = {
  children?: ReactNode;
};

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node,
};
